
CREATE TABLE AGENT (
	ID_AG CHAR(10) NOT NULL,
	NAME_AG CHAR(20) NOT NULL,
	TOWN CHAR(20),
	PHONE CHAR(10),
	CONSTRAINT PK_AGENT PRIMARY KEY (ID_AG)
);

CREATE TABLE GOODS (
	ID_GOODS CHAR(10) NOT NULL,
	NOMENCLATURE CHAR(20) NOT NULL,
	MEASURE CHAR(10),
	CONSTRAINT PK_GOODS PRIMARY KEY (ID_GOODS)
);


CREATE TABLE LOG_FILE (
	ID INTEGER NOT NULL,
	INFORM VARCHAR(200),
	USER_NAME CHAR(10),
	DDATA DATE,
	CONSTRAINT PK_LOG_FILE PRIMARY KEY (ID)
);
CREATE TABLE WAREHOUSE (
	ID_WH CHAR(10) NOT NULL,
	NAME CHAR(20) NOT NULL,
	TOWN CHAR(20),
	CONSTRAINT PK_WAREHOUSE PRIMARY KEY (ID_WH)
);
CREATE TABLE GOODS_WH (
	ID INTEGER NOT NULL,
	ID_WH CHAR(10) NOT NULL,
	ID_GOODS CHAR(10) NOT NULL,
	QUANTITY NUMERIC(15,2),
	CONSTRAINT PK_GOODS_WH PRIMARY KEY (ID),
	CONSTRAINT FK_GOODS_WH_1 FOREIGN KEY (ID_WH) REFERENCES WAREHOUSE(ID_WH),
	CONSTRAINT FK_GOODS_WH_2 FOREIGN KEY (ID_GOODS) REFERENCES GOODS(ID_GOODS)
);
CREATE INDEX FK_GOODS_WH_1 ON GOODS_WH (ID_WH);
CREATE INDEX FK_GOODS_WH_2 ON GOODS_WH (ID_GOODS);

CREATE TABLE OPERATION (
	ID INTEGER NOT NULL,
	ID_GOODS CHAR(10) NOT NULL,
	ID_AG CHAR(10) NOT NULL,
	ID_WH CHAR(10) NOT NULL,
	TYPEOP CHAR(1) NOT NULL,
	QUANTITY NUMERIC(15,2) NOT NULL,
	PRICE NUMERIC(15,2),
	OP_DATE DATE,
	CONSTRAINT PK_OPER PRIMARY KEY (ID),
	CONSTRAINT FK_OP_1 FOREIGN KEY (ID_GOODS) REFERENCES GOODS(ID_GOODS),
	CONSTRAINT FK_OP_2 FOREIGN KEY (ID_AG) REFERENCES AGENT(ID_AG),
	CONSTRAINT FK_OP_3 FOREIGN KEY (ID_WH) REFERENCES WAREHOUSE(ID_WH)
);
CREATE INDEX FK_OP_1 ON OPERATION (ID_GOODS);
CREATE INDEX FK_OP_2 ON OPERATION (ID_AG);
CREATE INDEX FK_OP_3 ON OPERATION (ID_WH);